CREATE TABLE IF NOT EXISTS usuario (USERNAME VARCHAR(30) NOT NULL, APELLIDO VARCHAR(30), DIRECCION VARCHAR(30), NOMBRE VARCHAR(30), PASSWORD VARCHAR(30), TELEFONO VARCHAR(30), PRIMARY KEY (USERNAME));

CREATE TABLE IF NOT EXISTS proveedor (USERNAME VARCHAR(30) NOT NULL, APELLIDO VARCHAR(30), DIRECCION VARCHAR(30), NOMBRE VARCHAR(30), PASSWORD VARCHAR(30), TELEFONO VARCHAR(30), PRIMARY KEY (USERNAME));

CREATE TABLE IF NOT EXISTS servicios (servicioId  SERIAL NOT NULL, CLIENTE VARCHAR(255), COST FLOAT, CUSTOMDATA VARCHAR(50000), DURATION BIGINT, FINISHTIME TIMESTAMP, PROVEEDOR VARCHAR(255), REVIEWCLIENTE INTEGER, REVIEWPROVEEDOR INTEGER, STARTTIME TIMESTAMP, STATUS VARCHAR(255), PRIMARY KEY (servicioId));